version: '3.8'
services:
  php:
    build: ./
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db